// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// SEARCH BOOK
export const SEARCH_BOOK_REQUEST = "SEARCH_BOOK_REQUEST";
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";
export const SEARCH_BOOK_FAILURE = "SEARCH_BOOK_FAILURE";

// SELECT BOOK
export const SELECT_BOOK_REQUEST = "SELECT_BOOK_REQUEST";
export const SELECT_BOOK_SUCCESS = "SELECT_BOOK_SUCCESS";
export const SELECT_BOOK_FAILURE = "SELECT_BOOK_FAILURE";

// POST UPLOADING
export const POST_UPLOADING_REQUEST = "POST_UPLOADING_REQUEST";
export const POST_UPLOADING_SUCCESS = "POST_UPLOADING_SUCCESS";
export const POST_UPLOADING_FAILURE = "POST_UPLOADING_FAILURE";

// POST LOADING
export const POST_LOADING_REQUEST = "POST_LOADING_REQUEST";
export const POST_LOADING_SUCCESS = "POST_LOADING_SUCCESS";
export const POST_LOADING_FAILURE = "POST_LOADING_FAILURE";

// POST DETAIL
export const POST_DETAIL_REQUEST = "POST_DETAIL_REQUEST";
export const POST_DETAIL_SUCCESS = "POST_DETAIL_SUCCESS";
export const POST_DETAIL_FAILURE = "POST_DETAIL_FAILURE";

// CATEGORY LOADING
export const CATEGORY_LOADING_REQUEST = "CATEGORY_LOADING_REQUEST";
export const CATEGORY_LOADING_SUCCESS = "CATEGORY_LOADING_SUCCESS";
export const CATEGORY_LOADING_FAILURE = "CATEGORY_LOADING_FAILURE";

// CATEGORY SELECT
export const CATEGORY_SELECT_REQUEST = "CATEGORY_SELECT_REQUEST";
export const CATEGORY_SELECT_SUCCESS = "CATEGORY_SELECT_SUCCESS";
export const CATEGORY_SELECT_FAILURE = "CATEGORY_SELECT_FAILURE";

// SEARCH
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

// POST DELETE
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

// POST EDIT
export const POST_EDIT_REQUEST = "POST_EDIT_REQUEST";
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS";
export const POST_EDIT_FAILURE = "POST_EDIT_FAILURE";
